// Code generated by MockGen. DO NOT EDIT.
// Source: operation.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	operation "db-worker/internal/config/operation"
	message "db-worker/internal/service/operation/message"
	uow "db-worker/internal/service/uow"
	storage "db-worker/internal/storage"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockunitOfWork is a mock of unitOfWork interface.
type MockunitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockunitOfWorkMockRecorder
}

// MockunitOfWorkMockRecorder is the mock recorder for MockunitOfWork.
type MockunitOfWorkMockRecorder struct {
	mock *MockunitOfWork
}

// NewMockunitOfWork creates a new mock instance.
func NewMockunitOfWork(ctrl *gomock.Controller) *MockunitOfWork {
	mock := &MockunitOfWork{ctrl: ctrl}
	mock.recorder = &MockunitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockunitOfWork) EXPECT() *MockunitOfWorkMockRecorder {
	return m.recorder
}

// BuildRequests mocks base method.
func (m *MockunitOfWork) BuildRequests(msg map[string]interface{}, driversMap map[string]uow.DriversMap, operation operation.Operation) (map[storage.Driver]*storage.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildRequests", msg, driversMap, operation)
	ret0, _ := ret[0].(map[storage.Driver]*storage.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildRequests indicates an expected call of BuildRequests.
func (mr *MockunitOfWorkMockRecorder) BuildRequests(msg, driversMap, operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildRequests", reflect.TypeOf((*MockunitOfWork)(nil).BuildRequests), msg, driversMap, operation)
}

// ExecRequests mocks base method.
func (m *MockunitOfWork) ExecRequests(ctx context.Context, requests map[storage.Driver]*storage.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecRequests", ctx, requests)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecRequests indicates an expected call of ExecRequests.
func (mr *MockunitOfWorkMockRecorder) ExecRequests(ctx, requests interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecRequests", reflect.TypeOf((*MockunitOfWork)(nil).ExecRequests), ctx, requests)
}

// StoragesMap mocks base method.
func (m *MockunitOfWork) StoragesMap() map[string]uow.DriversMap {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoragesMap")
	ret0, _ := ret[0].(map[string]uow.DriversMap)
	return ret0
}

// StoragesMap indicates an expected call of StoragesMap.
func (mr *MockunitOfWorkMockRecorder) StoragesMap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoragesMap", reflect.TypeOf((*MockunitOfWork)(nil).StoragesMap))
}

// MockmessageRepo is a mock of messageRepo interface.
type MockmessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockmessageRepoMockRecorder
}

// MockmessageRepoMockRecorder is the mock recorder for MockmessageRepo.
type MockmessageRepoMockRecorder struct {
	mock *MockmessageRepo
}

// NewMockmessageRepo creates a new mock instance.
func NewMockmessageRepo(ctrl *gomock.Controller) *MockmessageRepo {
	mock := &MockmessageRepo{ctrl: ctrl}
	mock.recorder = &MockmessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageRepo) EXPECT() *MockmessageRepoMockRecorder {
	return m.recorder
}

// CreateMany mocks base method.
func (m *MockmessageRepo) CreateMany(ctx context.Context, messages []message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MockmessageRepoMockRecorder) CreateMany(ctx, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*MockmessageRepo)(nil).CreateMany), ctx, messages)
}

// Get mocks base method.
func (m *MockmessageRepo) Get(ctx context.Context, id string) (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockmessageRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockmessageRepo)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockmessageRepo) GetAll(ctx context.Context) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockmessageRepoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockmessageRepo)(nil).GetAll), ctx)
}

// UpdateMany mocks base method.
func (m *MockmessageRepo) UpdateMany(ctx context.Context, messages []message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMany", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMany indicates an expected call of UpdateMany.
func (mr *MockmessageRepoMockRecorder) UpdateMany(ctx, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMany", reflect.TypeOf((*MockmessageRepo)(nil).UpdateMany), ctx, messages)
}

// MockmessageCreator is a mock of messageCreator interface.
type MockmessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockmessageCreatorMockRecorder
}

// MockmessageCreatorMockRecorder is the mock recorder for MockmessageCreator.
type MockmessageCreatorMockRecorder struct {
	mock *MockmessageCreator
}

// NewMockmessageCreator creates a new mock instance.
func NewMockmessageCreator(ctrl *gomock.Controller) *MockmessageCreator {
	mock := &MockmessageCreator{ctrl: ctrl}
	mock.recorder = &MockmessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageCreator) EXPECT() *MockmessageCreatorMockRecorder {
	return m.recorder
}

// CreateMany mocks base method.
func (m *MockmessageCreator) CreateMany(ctx context.Context, messages []message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MockmessageCreatorMockRecorder) CreateMany(ctx, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*MockmessageCreator)(nil).CreateMany), ctx, messages)
}

// MockmessageUpdater is a mock of messageUpdater interface.
type MockmessageUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockmessageUpdaterMockRecorder
}

// MockmessageUpdaterMockRecorder is the mock recorder for MockmessageUpdater.
type MockmessageUpdaterMockRecorder struct {
	mock *MockmessageUpdater
}

// NewMockmessageUpdater creates a new mock instance.
func NewMockmessageUpdater(ctrl *gomock.Controller) *MockmessageUpdater {
	mock := &MockmessageUpdater{ctrl: ctrl}
	mock.recorder = &MockmessageUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageUpdater) EXPECT() *MockmessageUpdaterMockRecorder {
	return m.recorder
}

// UpdateMany mocks base method.
func (m *MockmessageUpdater) UpdateMany(ctx context.Context, messages []message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMany", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMany indicates an expected call of UpdateMany.
func (mr *MockmessageUpdaterMockRecorder) UpdateMany(ctx, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMany", reflect.TypeOf((*MockmessageUpdater)(nil).UpdateMany), ctx, messages)
}

// MockmessageGetter is a mock of messageGetter interface.
type MockmessageGetter struct {
	ctrl     *gomock.Controller
	recorder *MockmessageGetterMockRecorder
}

// MockmessageGetterMockRecorder is the mock recorder for MockmessageGetter.
type MockmessageGetterMockRecorder struct {
	mock *MockmessageGetter
}

// NewMockmessageGetter creates a new mock instance.
func NewMockmessageGetter(ctrl *gomock.Controller) *MockmessageGetter {
	mock := &MockmessageGetter{ctrl: ctrl}
	mock.recorder = &MockmessageGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageGetter) EXPECT() *MockmessageGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockmessageGetter) Get(ctx context.Context, id string) (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockmessageGetterMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockmessageGetter)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockmessageGetter) GetAll(ctx context.Context) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockmessageGetterMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockmessageGetter)(nil).GetAll), ctx)
}

// MockmessageCounter is a mock of messageCounter interface.
type MockmessageCounter struct {
	ctrl     *gomock.Controller
	recorder *MockmessageCounterMockRecorder
}

// MockmessageCounterMockRecorder is the mock recorder for MockmessageCounter.
type MockmessageCounterMockRecorder struct {
	mock *MockmessageCounter
}

// NewMockmessageCounter creates a new mock instance.
func NewMockmessageCounter(ctrl *gomock.Controller) *MockmessageCounter {
	mock := &MockmessageCounter{ctrl: ctrl}
	mock.recorder = &MockmessageCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageCounter) EXPECT() *MockmessageCounterMockRecorder {
	return m.recorder
}

// AddFailedMessages mocks base method.
func (m *MockmessageCounter) AddFailedMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFailedMessages", count)
}

// AddFailedMessages indicates an expected call of AddFailedMessages.
func (mr *MockmessageCounterMockRecorder) AddFailedMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFailedMessages", reflect.TypeOf((*MockmessageCounter)(nil).AddFailedMessages), count)
}

// AddProcessedMessages mocks base method.
func (m *MockmessageCounter) AddProcessedMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcessedMessages", count)
}

// AddProcessedMessages indicates an expected call of AddProcessedMessages.
func (mr *MockmessageCounterMockRecorder) AddProcessedMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessedMessages", reflect.TypeOf((*MockmessageCounter)(nil).AddProcessedMessages), count)
}

// AddProcessingMessages mocks base method.
func (m *MockmessageCounter) AddProcessingMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcessingMessages", count)
}

// AddProcessingMessages indicates an expected call of AddProcessingMessages.
func (mr *MockmessageCounterMockRecorder) AddProcessingMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessingMessages", reflect.TypeOf((*MockmessageCounter)(nil).AddProcessingMessages), count)
}

// AddTotalMessages mocks base method.
func (m *MockmessageCounter) AddTotalMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTotalMessages", count)
}

// AddTotalMessages indicates an expected call of AddTotalMessages.
func (mr *MockmessageCounterMockRecorder) AddTotalMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTotalMessages", reflect.TypeOf((*MockmessageCounter)(nil).AddTotalMessages), count)
}

// AddValidatedMessages mocks base method.
func (m *MockmessageCounter) AddValidatedMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddValidatedMessages", count)
}

// AddValidatedMessages indicates an expected call of AddValidatedMessages.
func (mr *MockmessageCounterMockRecorder) AddValidatedMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddValidatedMessages", reflect.TypeOf((*MockmessageCounter)(nil).AddValidatedMessages), count)
}

// DecrementFailedMessagesBy mocks base method.
func (m *MockmessageCounter) DecrementFailedMessagesBy(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecrementFailedMessagesBy", count)
}

// DecrementFailedMessagesBy indicates an expected call of DecrementFailedMessagesBy.
func (mr *MockmessageCounterMockRecorder) DecrementFailedMessagesBy(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementFailedMessagesBy", reflect.TypeOf((*MockmessageCounter)(nil).DecrementFailedMessagesBy), count)
}

// DecrementProcessingMessagesBy mocks base method.
func (m *MockmessageCounter) DecrementProcessingMessagesBy(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecrementProcessingMessagesBy", count)
}

// DecrementProcessingMessagesBy indicates an expected call of DecrementProcessingMessagesBy.
func (mr *MockmessageCounterMockRecorder) DecrementProcessingMessagesBy(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementProcessingMessagesBy", reflect.TypeOf((*MockmessageCounter)(nil).DecrementProcessingMessagesBy), count)
}

// MockmessageAdder is a mock of messageAdder interface.
type MockmessageAdder struct {
	ctrl     *gomock.Controller
	recorder *MockmessageAdderMockRecorder
}

// MockmessageAdderMockRecorder is the mock recorder for MockmessageAdder.
type MockmessageAdderMockRecorder struct {
	mock *MockmessageAdder
}

// NewMockmessageAdder creates a new mock instance.
func NewMockmessageAdder(ctrl *gomock.Controller) *MockmessageAdder {
	mock := &MockmessageAdder{ctrl: ctrl}
	mock.recorder = &MockmessageAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageAdder) EXPECT() *MockmessageAdderMockRecorder {
	return m.recorder
}

// AddFailedMessages mocks base method.
func (m *MockmessageAdder) AddFailedMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFailedMessages", count)
}

// AddFailedMessages indicates an expected call of AddFailedMessages.
func (mr *MockmessageAdderMockRecorder) AddFailedMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFailedMessages", reflect.TypeOf((*MockmessageAdder)(nil).AddFailedMessages), count)
}

// AddProcessedMessages mocks base method.
func (m *MockmessageAdder) AddProcessedMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcessedMessages", count)
}

// AddProcessedMessages indicates an expected call of AddProcessedMessages.
func (mr *MockmessageAdderMockRecorder) AddProcessedMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessedMessages", reflect.TypeOf((*MockmessageAdder)(nil).AddProcessedMessages), count)
}

// AddProcessingMessages mocks base method.
func (m *MockmessageAdder) AddProcessingMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcessingMessages", count)
}

// AddProcessingMessages indicates an expected call of AddProcessingMessages.
func (mr *MockmessageAdderMockRecorder) AddProcessingMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessingMessages", reflect.TypeOf((*MockmessageAdder)(nil).AddProcessingMessages), count)
}

// AddTotalMessages mocks base method.
func (m *MockmessageAdder) AddTotalMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTotalMessages", count)
}

// AddTotalMessages indicates an expected call of AddTotalMessages.
func (mr *MockmessageAdderMockRecorder) AddTotalMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTotalMessages", reflect.TypeOf((*MockmessageAdder)(nil).AddTotalMessages), count)
}

// AddValidatedMessages mocks base method.
func (m *MockmessageAdder) AddValidatedMessages(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddValidatedMessages", count)
}

// AddValidatedMessages indicates an expected call of AddValidatedMessages.
func (mr *MockmessageAdderMockRecorder) AddValidatedMessages(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddValidatedMessages", reflect.TypeOf((*MockmessageAdder)(nil).AddValidatedMessages), count)
}

// MockmessageDecrementer is a mock of messageDecrementer interface.
type MockmessageDecrementer struct {
	ctrl     *gomock.Controller
	recorder *MockmessageDecrementerMockRecorder
}

// MockmessageDecrementerMockRecorder is the mock recorder for MockmessageDecrementer.
type MockmessageDecrementerMockRecorder struct {
	mock *MockmessageDecrementer
}

// NewMockmessageDecrementer creates a new mock instance.
func NewMockmessageDecrementer(ctrl *gomock.Controller) *MockmessageDecrementer {
	mock := &MockmessageDecrementer{ctrl: ctrl}
	mock.recorder = &MockmessageDecrementerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageDecrementer) EXPECT() *MockmessageDecrementerMockRecorder {
	return m.recorder
}

// DecrementFailedMessagesBy mocks base method.
func (m *MockmessageDecrementer) DecrementFailedMessagesBy(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecrementFailedMessagesBy", count)
}

// DecrementFailedMessagesBy indicates an expected call of DecrementFailedMessagesBy.
func (mr *MockmessageDecrementerMockRecorder) DecrementFailedMessagesBy(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementFailedMessagesBy", reflect.TypeOf((*MockmessageDecrementer)(nil).DecrementFailedMessagesBy), count)
}

// DecrementProcessingMessagesBy mocks base method.
func (m *MockmessageDecrementer) DecrementProcessingMessagesBy(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecrementProcessingMessagesBy", count)
}

// DecrementProcessingMessagesBy indicates an expected call of DecrementProcessingMessagesBy.
func (mr *MockmessageDecrementerMockRecorder) DecrementProcessingMessagesBy(count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementProcessingMessagesBy", reflect.TypeOf((*MockmessageDecrementer)(nil).DecrementProcessingMessagesBy), count)
}
