// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	storage "db-worker/internal/storage"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockrequestsRepo is a mock of requestsRepo interface.
type MockrequestsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockrequestsRepoMockRecorder
}

// MockrequestsRepoMockRecorder is the mock recorder for MockrequestsRepo.
type MockrequestsRepoMockRecorder struct {
	mock *MockrequestsRepo
}

// NewMockrequestsRepo creates a new mock instance.
func NewMockrequestsRepo(ctrl *gomock.Controller) *MockrequestsRepo {
	mock := &MockrequestsRepo{ctrl: ctrl}
	mock.recorder = &MockrequestsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrequestsRepo) EXPECT() *MockrequestsRepoMockRecorder {
	return m.recorder
}

// GetAllTransactionsByFields mocks base method.
func (m *MockrequestsRepo) GetAllTransactionsByFields(ctx context.Context, fields map[string]any) ([]storage.TransactionModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactionsByFields", ctx, fields)
	ret0, _ := ret[0].([]storage.TransactionModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTransactionsByFields indicates an expected call of GetAllTransactionsByFields.
func (mr *MockrequestsRepoMockRecorder) GetAllTransactionsByFields(ctx, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactionsByFields", reflect.TypeOf((*MockrequestsRepo)(nil).GetAllTransactionsByFields), ctx, fields)
}

// UpdateStatusMany mocks base method.
func (m *MockrequestsRepo) UpdateStatusMany(ctx context.Context, ids []string, status, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusMany", ctx, ids, status, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusMany indicates an expected call of UpdateStatusMany.
func (mr *MockrequestsRepoMockRecorder) UpdateStatusMany(ctx, ids, status, errMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusMany", reflect.TypeOf((*MockrequestsRepo)(nil).UpdateStatusMany), ctx, ids, status, errMsg)
}
